'use client';

import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { useThemeStore } from '@/store/themeStore';
import { baseTokenClass, darkThemeClass, lightThemeClass } from '@/theme/theme.css';

import './global-style.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Turborepo",
//   description: "Generated by create turbo",
// };

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  const { darkMode } = useThemeStore();

  return (
    <html lang="en" className={clsx(inter.className)}>
      <body className={clsx(baseTokenClass, darkMode ? darkThemeClass : lightThemeClass)}>
        {children}
      </body>
    </html>
  );
}
