'use client';

import clsx from 'clsx';
import type { Metadata } from 'next';
import { Noto_Sans as NotoSans, Noto_Sans_KR as NotoSansKR } from 'next/font/google';
import { HiMoon, HiSun } from 'react-icons/hi';

import { Box } from '@/components/atom/Box';
import { Button } from '@/components/atom/Button';
import { Text } from '@/components/atom/Text';
import { useThemeStore } from '@/store/themeStore';
import { baseTokenClass, darkThemeClass, lightThemeClass } from '@/theme/theme.css';

import './global-style.css';
import './globals.css';

const notoSans = NotoSans({ subsets: ['latin'] });
const notoSansKR = NotoSansKR({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: "Create Turborepo",
//   description: "Generated by create turbo",
// };

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  const { darkMode, toggleDarkMode } = useThemeStore();

  return (
    <html lang="en" className={clsx(notoSans.className, notoSansKR.className)}>
      <body className={clsx(baseTokenClass, darkMode ? darkThemeClass : lightThemeClass)}>
        <Box
          display={'flex'}
          flexDirection={'column'}
          alignItems={'center'}
          justifyContent={'center'}
          height={'full'}
          gap={'1'}
        >
          <Box
            backgroundColor={'background.container'}
            minWidth={{ all: '280', '2xl': '360' }}
            padding={{ all: '4', '2xl': '6' }}
            borderRadius={{ all: 'sm', '2xl': 'md' }}
            borderBottomLeftRadius={{ all: '0', '2xl': '0' }}
            borderBottomRightRadius={{ all: '0', '2xl': '0' }}
          >
            <Box display={'flex'} flexDirection={'row'} justifyContent={'space-between'}>
              <Box
                display={'flex'}
                flexDirection={'row'}
                alignItems={'center'}
                fontSize={{ all: '30', '2xl': '36' }}
              >
                <Text fontWeight="heavy">Typro</Text>
                <Text fontWeight="heavy" opacity={'disabled'}>
                  grammer
                </Text>
              </Box>
              <Button onClick={toggleDarkMode}>
                <Box display="flex" paddingX="2">
                  {darkMode ? <HiSun /> : <HiMoon />}
                </Box>
              </Button>
            </Box>
          </Box>

          <Box
            backgroundColor={'background.container'}
            padding={{ all: '4', '2xl': '6' }}
            minWidth={{ all: '280', '2xl': '360' }}
            borderRadius={{ all: 'sm', '2xl': 'md' }}
            borderTopLeftRadius={{ all: '0', '2xl': '0' }}
            borderTopRightRadius={{ all: '0', '2xl': '0' }}
          >
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
